FROM maven:4.0.0-rc-5-eclipse-temurin-25-noble AS build

WORKDIR /workspace
COPY pom.xml ./
COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:25

WORKDIR /app

COPY --from=build /workspace/target/classes ./target/classes

ENV JAVA_TOOL_OPTIONS="-XX:ActiveProcessorCount=4 -Xms512m -Xmx512m"

EXPOSE 6379

CMD ["java", "-cp", "target/classes", "org.perfect047.Main"]